# Generated by Django 4.2.3 on 2023-11-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_maquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='descripcion',
        ),
    ]
