# Generated by Django 4.2.3 on 2023-11-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_remove_maquina_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
